# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\AHMAD\DESKTOP\xodesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
import random 
import time
letter='O'
letter2='X'
yourscorenmb=0 
aiscorenmb=0 
turn='k'

class Ui_TicTacToe(object):
    def setupUi(self, TicTacToe):
        TicTacToe.setObjectName("TicTacToe")
        TicTacToe.setFixedSize(800, 600)
        TicTacToe.setWindowFlag(QtCore.Qt.WindowCloseButtonHint, False)
        TicTacToe.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        TicTacToe.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(TicTacToe)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setStyleSheet("background-color: rgb(88, 99, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.box1 = QtWidgets.QPushButton(self.frame)
        self.box1.setGeometry(QtCore.QRect(200, 70, 111, 91))
        self.box1.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.box1.setMouseTracking(True)
        self.box1.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"font: 48pt \"Showcard Gothic\";\n"
"border: 1px solid red;\n"
"border-radius:20px;\n"
"border-color: rgb(255, 0, 0);")
        self.box1.setText("")
        self.box1.setObjectName("box1")
        self.box2 = QtWidgets.QPushButton(self.frame)
        self.box2.setGeometry(QtCore.QRect(320, 70, 111, 91))
        self.box2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.box2.setMouseTracking(True)
        self.box2.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: 1px solid red;\n"
"border-radius:20px;\n"
"border-color: rgb(255, 0, 0);\n"
"font: 48pt \"Showcard Gothic\";")
        self.box2.setText("")
        self.box2.setObjectName("box2")
        self.box3 = QtWidgets.QPushButton(self.frame)
        self.box3.setGeometry(QtCore.QRect(440, 70, 111, 91))
        self.box3.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.box3.setMouseTracking(True)
        self.box3.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: 1px solid red;\n"
"border-radius:20px;\n"
"border-color: rgb(255, 0, 0);\n"
"font: 48pt \"Showcard Gothic\";")
        self.box3.setText("")
        self.box3.setObjectName("box3")
        self.box4 = QtWidgets.QPushButton(self.frame)
        self.box4.setGeometry(QtCore.QRect(200, 170, 111, 91))
        self.box4.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.box4.setMouseTracking(True)
        self.box4.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: 1px solid red;\n"
"border-radius:20px;\n"
"border-color: rgb(255, 0, 0);\n"
"font: 48pt \"Showcard Gothic\";")
        self.box4.setText("")
        self.box4.setObjectName("box4")
        self.box5 = QtWidgets.QPushButton(self.frame)
        self.box5.setGeometry(QtCore.QRect(320, 170, 111, 91))
        self.box5.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.box5.setMouseTracking(True)
        self.box5.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: 1px solid red;\n"
"border-radius:20px;\n"
"border-color: rgb(255, 0, 0);\n"
"font: 48pt \"Showcard Gothic\";")
        self.box5.setText("")
        self.box5.setObjectName("box5")
        self.box6 = QtWidgets.QPushButton(self.frame)
        self.box6.setGeometry(QtCore.QRect(440, 170, 111, 91))
        self.box6.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.box6.setMouseTracking(True)
        self.box6.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: 1px solid red;\n"
"border-radius:20px;\n"
"border-color: rgb(255, 0, 0);\n"
"font: 48pt \"Showcard Gothic\";")
        self.box6.setText("")
        self.box6.setObjectName("box6")
        self.box7 = QtWidgets.QPushButton(self.frame)
        self.box7.setGeometry(QtCore.QRect(200, 270, 111, 91))
        self.box7.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.box7.setMouseTracking(True)
        self.box7.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: 1px solid red;\n"
"border-radius:20px;\n"
"border-color: rgb(255, 0, 0);\n"
"font: 48pt \"Showcard Gothic\";")
        self.box7.setText("")
        self.box7.setObjectName("box7")
        self.box8 = QtWidgets.QPushButton(self.frame)
        self.box8.setGeometry(QtCore.QRect(320, 270, 111, 91))
        self.box8.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.box8.setMouseTracking(True)
        self.box8.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: 1px solid red;\n"
"border-radius:20px;\n"
"border-color: rgb(255, 0, 0);\n"
"font: 48pt \"Showcard Gothic\";")
        self.box8.setText("")
        self.box8.setObjectName("box8")
        self.box9 = QtWidgets.QPushButton(self.frame)
        self.box9.setGeometry(QtCore.QRect(440, 270, 111, 91))
        self.box9.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.box9.setMouseTracking(True)
        self.box9.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: 1px solid red;\n"
"border-radius:20px;\n"
"border-color: rgb(255, 0, 0);\n"
"font: 48pt \"Showcard Gothic\";")
        self.box9.setText("")
        self.box9.setObjectName("box9")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(640, 70, 141, 291))
        self.textEdit.setStyleSheet("font: 14pt \"Rockwell\";\n"
"border-color: rgb(0, 0, 0);\n"
"border: 3px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 0, 641, 51))
        self.label.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 24pt \"Showcard Gothic\";")
        self.label.setObjectName("label")
        self.Reset = QtWidgets.QPushButton(self.frame)
        self.Reset.setGeometry(QtCore.QRect(150, 470, 160, 81))
        self.Reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Reset.setMouseTracking(True)
        self.Reset.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 32pt \"Pristina\";\n"
"border:2px solid rgb(88,99,255);\n"
"border-radius:20px")
        self.Reset.setObjectName("Reset")
        self.Exit = QtWidgets.QPushButton(self.frame)
        self.Exit.setGeometry(QtCore.QRect(500, 470, 160, 81))
        self.Exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Exit.setMouseTracking(True)
        self.Exit.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 32pt \"Pristina\";\n"
"border:2px solid rgb(88,99,255);\n"
"border-radius:20px")
        self.Exit.setObjectName("Exit")
        self.yourscore = QtWidgets.QLabel(self.frame)
        self.yourscore.setGeometry(QtCore.QRect(10, 380, 191, 61))
        self.yourscore.setStyleSheet("font: 18pt \"Segoe Print\";\n"
"text-decoration: line-through;\n"
"background-color: rgb(170, 170, 255);\n"
"border: 1px solid red;\n"
"border-radius:20px;\n"
"border-color: rgb(255, 0, 0);")
        self.yourscore.setObjectName("yourscore")
        self.aiscore = QtWidgets.QLabel(self.frame)
        self.aiscore.setGeometry(QtCore.QRect(590, 380, 191, 61))
        self.aiscore.setStyleSheet("font: 18pt \"Segoe Print\";\n"
"text-decoration: line-through;\n"
"background-color: rgb(170, 170, 255);\n"
"border: 1px solid red;\n"
"border-radius:20px;\n"
"border-color: rgb(255, 0, 0);")
        self.aiscore.setObjectName("aiscore")
        self.ResetScore = QtWidgets.QPushButton(self.frame)
        self.ResetScore.setGeometry(QtCore.QRect(760, 5, 21, 21))
        self.ResetScore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ResetScore.setMouseTracking(True)
        self.ResetScore.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 26pt \"Pristina\";\n"
"border:2px solid rgb(88,99,255);\n"
"border-radius:8px")
        self.ResetScore.setText("")
        self.ResetScore.setObjectName("ResetScore")
        TicTacToe.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TicTacToe)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menubar.setObjectName("menubar")
        TicTacToe.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TicTacToe)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        TicTacToe.setStatusBar(self.statusbar)

        self.retranslateUi(TicTacToe)
        QtCore.QMetaObject.connectSlotsByName(TicTacToe)
#my code 
        
        self.box1.clicked.connect(lambda: self.put(1))
        self.box2.clicked.connect(lambda: self.put(2))
        self.box3.clicked.connect(lambda: self.put(3))
        self.box4.clicked.connect(lambda: self.put(4))
        self.box5.clicked.connect(lambda: self.put(5))
        self.box6.clicked.connect(lambda: self.put(6))
        self.box7.clicked.connect(lambda: self.put(7))
        self.box8.clicked.connect(lambda: self.put(8))
        self.box9.clicked.connect(lambda: self.put(9))
        self.Reset.clicked.connect(self.reset)
        self.Exit.clicked.connect(self.exit1)
        self.ResetScore.clicked.connect(self.rst)
    def rst(self):
        global aiscorenmb
        global yourscorenmb
        aiscorenmb=0
        yourscorenmb=0
        self.yourscore.setText('Your Score: {}' .format(str(yourscorenmb)))
        self.aiscore.setText('AI Score: {}' .format(str(aiscorenmb)))
    def exit1(self):
            exit()
    def reset(self):
        #return the buttons to the initial form
        self.box1.setText('')
        self.box2.setText('')
        self.box3.setText('')
        self.box4.setText('')
        self.box5.setText('')
        self.box6.setText('')
        self.box7.setText('')
        self.box8.setText('')
        self.box9.setText('')

        self.box1.setEnabled(True)
        self.box2.setEnabled(True)
        self.box3.setEnabled(True)
        self.box4.setEnabled(True)
        self.box5.setEnabled(True)
        self.box6.setEnabled(True)
        self.box7.setEnabled(True)
        self.box8.setEnabled(True)
        self.box9.setEnabled(True)
        self.box1.setStyleSheet("background-color: rgb(170, 170, 255);border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;")
        self.box2.setStyleSheet("background-color: rgb(170, 170, 255);border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;")
        self.box3.setStyleSheet("background-color: rgb(170, 170, 255);border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;")
        self.box4.setStyleSheet("background-color: rgb(170, 170, 255);border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;")
        self.box5.setStyleSheet("background-color: rgb(170, 170, 255);border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;")
        self.box6.setStyleSheet("background-color: rgb(170, 170, 255);border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;")
        self.box7.setStyleSheet("background-color: rgb(170, 170, 255);border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;")
        self.box8.setStyleSheet("background-color: rgb(170, 170, 255);border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;")
        self.box9.setStyleSheet("background-color: rgb(170, 170, 255);border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;")
        
        if turn=='aiturn':
                self.botdecision()
        
    def changecolor(self,whichsign,color):
        if self.box1.text()==whichsign and self.box2.text()==whichsign and self.box3.text()==whichsign:
                        self.box1.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box2.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box3.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
        elif self.box4.text()==whichsign and self.box5.text()==whichsign and self.box6.text()==whichsign:
                        self.box4.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box5.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box6.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
        elif self.box7.text()==whichsign and self.box8.text()==whichsign and self.box9.text()==whichsign:
                        self.box7.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box8.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box9.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
        elif self.box1.text()==whichsign and self.box4.text()==whichsign and self.box7.text()==whichsign:
                        self.box1.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box4.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box7.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
        elif self.box2.text()==whichsign and self.box5.text()==whichsign and self.box8.text()==whichsign:
                        self.box2.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box5.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box8.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
        elif self.box3.text()==whichsign and self.box6.text()==whichsign and self.box9.text()==whichsign:
                        self.box3.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box9.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box6.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
        elif self.box1.text()==whichsign and self.box5.text()==whichsign and self.box9.text()==whichsign:
                        self.box1.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box5.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box9.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
        elif self.box3.text()==whichsign and self.box5.text()==whichsign and self.box7.text()==whichsign:
                        self.box3.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box5.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
                        self.box7.setStyleSheet("background-color: {};border: 1px solid red;border-radius:20px;border-color: rgb(255, 0, 0);font: 48pt Showcard Gothic;color:white;".format(color))
    def checkwinner(self,whichsign, winner):
        if (self.box1.text()==whichsign and self.box2.text()==whichsign and self.box3.text()==whichsign) or (self.box4.text()==whichsign and self.box5.text()==whichsign and self.box6.text()==whichsign) or (self.box7.text()==whichsign and self.box8.text()==whichsign and self.box9.text()==whichsign) or (self.box1.text()==whichsign and self.box4.text()==whichsign and self.box7.text()==whichsign) or (self.box2.text()==whichsign and self.box5.text()==whichsign and self.box8.text()==whichsign) or (self.box3.text()==whichsign and self.box6.text()==whichsign and self.box9.text()==whichsign) or (self.box1.text()==whichsign and self.box5.text()==whichsign and self.box9.text()==whichsign)or (self.box3.text()==whichsign and self.box5.text()==whichsign and self.box7.text()==whichsign):
                
                self.box1.setEnabled(False)
                self.box2.setEnabled(False)
                self.box3.setEnabled(False)
                self.box4.setEnabled(False)
                self.box5.setEnabled(False)
                self.box6.setEnabled(False)
                self.box7.setEnabled(False)
                self.box8.setEnabled(False)
                self.box9.setEnabled(False)
                self.changecolor('X','green')
                self.changecolor('O','red')
                if whichsign=='O': 
                        global aiscorenmb
                        aiscorenmb+=1
                        self.aiscore.setText('AI Score:{}' .format(str(aiscorenmb)))
                elif whichsign=='X':
                        global yourscorenmb
                        yourscorenmb+=1
                        self.yourscore.setText('Your Score: {}' .format(str(yourscorenmb)))
                
                global turn
                
                if turn=='aiturn':
                        turn='woh'
                else:
                        turn='aiturn'
                print(turn)
                

                


                
        if (self.box1.text()!='' and self.box2.text()!='' and self.box3.text()!='' and self.box4.text()!='' and self.box5.text()!='' and self.box6.text()!='' and self.box7.text()!='' and self.box8.text()!='' and self.box9.text()!=''):
                
                self.box1.setEnabled(False)
                self.box2.setEnabled(False)
                self.box3.setEnabled(False)
                self.box4.setEnabled(False)
                self.box5.setEnabled(False)
                self.box6.setEnabled(False)
                self.box7.setEnabled(False)
                self.box8.setEnabled(False)
                self.box9.setEnabled(False)
                
                if turn=='aiturn':
                        turn='woh'
                else:
                        turn='aiturn'
                print(turn)


    def botdecide(self,pos):
        if pos==1:self.box1.setText('O')
        if pos==2:self.box2.setText('O')
        if pos==3:self.box3.setText('O')
        if pos==4:self.box4.setText('O')
        if pos==5:self.box5.setText('O')
        if pos==6:self.box6.setText('O')
        if pos==7:self.box7.setText('O')
        if pos==8:self.box8.setText('O')
        if pos==9:self.box9.setText('O')
        
    def botdecision(self):
        time.sleep(0.05)
        rndm=random.randint(1,10)
        

        if self.box2.text()==letter and self.box3.text()==letter and self.box1.text()=='' :self.botdecide(1)
        elif self.box1.text()==letter and self.box2.text()==letter and self.box3.text()=='':self.botdecide(3)
        elif self.box1.text()==letter and self.box3.text()==letter and self.box2.text()=='': self.botdecide(2)
        elif self.box4.text()==letter and self.box5.text()==letter and self.box6.text()=='': self.botdecide(6)
        elif self.box4.text()==letter and self.box6.text()==letter and self.box5.text()=='':self.botdecide(5)
        elif self.box5.text()==letter and self.box6.text()==letter and self.box4.text()=='':self.botdecide(4)
        elif self.box7.text()==letter and self.box8.text()==letter and self.box9.text()=='':self.botdecide(9)
        elif self.box7.text()==letter and self.box9.text()==letter and self.box8.text()=='':self.botdecide(8)
        elif self.box8.text()==letter and self.box9.text()==letter and self.box7.text()=='':self.botdecide(7)
        elif self.box1.text()==letter and self.box4.text()==letter and self.box7.text()=='':self.botdecide(7)
        elif self.box1.text()==letter and self.box7.text()==letter and self.box4.text()=='':self.botdecide(4)
        elif self.box4.text()==letter and self.box7.text()==letter and self.box1.text()=='':self.botdecide(1)
        elif self.box2.text()==letter and self.box5.text()==letter and self.box8.text()=='':self.botdecide(8)
        elif self.box2.text()==letter and self.box8.text()==letter and self.box5.text()=='':self.botdecide(5)
        elif self.box5.text()==letter and self.box8.text()==letter  and self.box2.text()=='':self.botdecide(2)
        elif self.box3.text()==letter and self.box6.text()==letter and self.box9.text()=='':self.botdecide(9)
        elif self.box3.text()==letter and self.box9.text()==letter and self.box6.text()=='':self.botdecide(6)
        elif self.box6.text()==letter and self.box9.text()==letter and self.box3.text()=='':self.botdecide(3)
        elif self.box1.text()==letter and self.box5.text()==letter  and self.box9.text()=='':self.botdecide(9)
        elif self.box1.text()==letter and self.box9.text()==letter and self.box5.text()=='':self.botdecide(5)
        elif self.box5.text()==letter and self.box9.text()==letter and self.box1.text()=='':self.botdecide(1)
        elif self.box3.text()==letter and self.box5.text()==letter and self.box7.text()=='':self.botdecide(7)
        elif self.box3.text()==letter and self.box7.text()==letter and self.box5.text()=='':self.botdecide(5)
        elif self.box5.text()==letter and self.box7.text()==letter and self.box3.text()=='':self.botdecide(3)

                
        elif self.box2.text()==letter2 and self.box3.text()==letter2 and self.box1.text()=='': self.botdecide(1)
        elif self.box1.text()==letter2 and self.box2.text()==letter2 and self.box3.text()=='' :self.botdecide(3)
        elif self.box1.text()==letter2 and self.box3.text()==letter2 and self.box2.text()=='': self.botdecide(2)
        elif self.box4.text()==letter2 and self.box5.text()==letter2 and self.box6.text()=='': self.botdecide(6)
        elif self.box4.text()==letter2 and self.box6.text()==letter2 and self.box5.text()=='':self.botdecide(5)
        elif self.box5.text()==letter2 and self.box6.text()==letter2 and self.box4.text()=='':self.botdecide(4)
        elif self.box7.text()==letter2 and self.box8.text()==letter2 and self.box9.text()=='':self.botdecide(9)
        elif self.box7.text()==letter2 and self.box9.text()==letter2 and self.box8.text()=='':self.botdecide(8)
        elif self.box8.text()==letter2 and self.box9.text()==letter2 and self.box7.text()=='':self.botdecide(7)
        elif self.box1.text()==letter2 and self.box4.text()==letter2 and self.box7.text()=='':self.botdecide(7)
        elif self.box1.text()==letter2 and self.box7.text()==letter2 and self.box4.text()=='':self.botdecide(4)
        elif self.box4.text()==letter2 and self.box7.text()==letter2 and self.box1.text()=='':self.botdecide(1)
        elif self.box2.text()==letter2 and self.box5.text()==letter2 and self.box8.text()=='':self.botdecide(8)
        elif self.box2.text()==letter2 and self.box8.text()==letter2 and self.box5.text()=='':self.botdecide(5)
        elif self.box5.text()==letter2 and self.box8.text()==letter2  and self.box2.text()=='':self.botdecide(2)
        elif self.box3.text()==letter2 and self.box6.text()==letter2 and self.box9.text()=='':self.botdecide(9)
        elif self.box3.text()==letter2 and self.box9.text()==letter2 and self.box6.text()=='':self.botdecide(6)
        elif self.box5.text()==letter2 and self.box1.text()==letter2  and self.box9.text()=='':self.botdecide(9)
        elif self.box1.text()==letter2 and self.box9.text()==letter2 and self.box5.text()=='':self.botdecide(5)
        elif self.box5.text()==letter2 and self.box9.text()==letter2 and self.box1.text()=='':self.botdecide(1)
        elif self.box3.text()==letter2 and self.box5.text()==letter2 and self.box7.text()=='':self.botdecide(7)
        elif self.box3.text()==letter2 and self.box7.text()==letter2 and self.box5.text()=='':self.botdecide(5)
        elif self.box5.text()==letter2 and self.box7.text()==letter2 and self.box3.text()=='':self.botdecide(3)
        elif rndm>8 and self.box5.text()=='': self.botdecide(5)
        elif rndm<2 and self.box3.text()=='': self.botdecide(3)
        elif rndm ==5 and self.box9.text()=='':self.botdecide(9)
                
        else:
                try:
                        ok=random.randint(1,9)
                        # if the number generated has a letter in it the program changes 'ok'
                        while (ok==1 and self.box1.text()!='') or(ok==2 and self.box2.text()!='') or ( ok==3 and self.box3.text()!='') or (ok==4 and self.box4.text()!='')or (ok==5 and self.box5.text()!='') or (ok==6 and self.box6.text()!='')or (ok==7 and self.box7.text()!='') or (ok==8 and self.box8.text()!='') or (ok==9 and self.box9.text()!=''):
                                ok=random.randint(1,9)
                                
                                
                        #if the number generated got no letter the program fills the box with 'O'
                        if ok==1 and self.box1.text()=='':self.box1.setText('O')
                        elif ok==2 and self.box2.text()=='':self.box2.setText('O')
                        elif ok==3 and self.box3.text()=='':self.box3.setText('O')
                        elif ok==4 and self.box4.text()=='':self.box4.setText('O')
                        elif ok==5 and self.box5.text()=='':self.box5.setText('O')
                        elif ok==6 and self.box6.text()=='':self.box6.setText('O')
                        elif ok==7 and self.box7.text()=='':self.box7.setText('O')
                        elif ok==8 and self.box8.text()=='':self.box8.setText('O')
                        elif ok==9 and self.box9.text()=='':self.box9.setText('O')
                        
                                
                except:
                        temp=1
                
        
        
    # function for clicking the box 
    def put(self,pos):
        if pos==1:
            if self.box1.text()=='':
                # if it was the last box in the game so >>>>> to avoid crashing the program
                if  (self.box1.text()=='' and self.box2.text()!='' and self.box3.text()!='' and self.box4.text()!='' and self.box5.text()!='' and self.box6.text()!='' and self.box7.text()!='' and self.box8.text()!='' and self.box9.text()!=''):
                        self.box1.setText('X')
                        self.checkwinner('X','You')  
                else:
                        self.box1.setText('X')
                        self.checkwinner('X','You')
                        self.botdecision()
                        self.checkwinner('O','Bot')
                
        if pos==2:
            if self.box2.text()=='':
                if  (self.box1.text()!='' and self.box2.text()=='' and self.box3.text()!='' and self.box4.text()!='' and self.box5.text()!='' and self.box6.text()!='' and self.box7.text()!='' and self.box8.text()!='' and self.box9.text()!=''):
                        self.box2.setText('X')
                        self.checkwinner('X','You')  
                else:
                        self.box2.setText('X')
                        self.checkwinner('X','You')
                        self.botdecision()
                        self.checkwinner('O','Bot')
        if pos==3:
            if self.box3.text()=='':
                if  (self.box1.text()!='' and self.box2.text()!='' and self.box3.text()=='' and self.box4.text()!='' and self.box5.text()!='' and self.box6.text()!='' and self.box7.text()!='' and self.box8.text()!='' and self.box9.text()!=''):
                        self.box3.setText('X')
                        self.checkwinner('X','You')  
                else:
                        self.box3.setText('X')
                        self.checkwinner('X','You')
                        self.botdecision()
                        self.checkwinner('O','Bot')
        if pos==4:
            if self.box4.text()=='':
                if  (self.box1.text()=='' and self.box2.text()!='' and self.box3.text()!='' and self.box4.text()=='' and self.box5.text()!='' and self.box6.text()!='' and self.box7.text()!='' and self.box8.text()!='' and self.box9.text()!=''):
                        self.box4.setText('X')
                        self.checkwinner('X','You')  
                else:
                        self.box4.setText('X')
                        self.checkwinner('X','You')
                        self.botdecision()
                        self.checkwinner('O','Bot')
        if pos==5:
            if self.box5.text()=='':
                if  (self.box1.text()!='' and self.box2.text()!='' and self.box3.text()!='' and self.box4.text()!='' and self.box5.text()=='' and self.box6.text()!='' and self.box7.text()!='' and self.box8.text()!='' and self.box9.text()!=''):
                        self.box5.setText('X')
                        self.checkwinner('X','You')  
                else:
                        self.box5.setText('X')
                        self.checkwinner('X','You')
                        self.botdecision()
                        self.checkwinner('O','Bot')
        if pos==6:
            if self.box6.text()=='':
                if  (self.box1.text()!='' and self.box2.text()!='' and self.box3.text()!='' and self.box4.text()!='' and self.box5.text()!='' and self.box6.text()=='' and self.box7.text()!='' and self.box8.text()!='' and self.box9.text()!=''):
                        self.box6.setText('X')
                        self.checkwinner('X','You')  
                else:
                        self.box6.setText('X')
                        self.checkwinner('X','You')
                        self.botdecision()
                        self.checkwinner('O','Bot')
        if pos==7:
            if self.box7.text()=='':
                if  (self.box1.text()!='' and self.box2.text()!='' and self.box3.text()!='' and self.box4.text()!='' and self.box5.text()!='' and self.box6.text()!='' and self.box7.text()=='' and self.box8.text()!='' and self.box9.text()!=''):
                        self.box7.setText('X')
                        self.checkwinner('X','You')  
                else:
                        self.box7.setText('X')
                        self.checkwinner('X','You')
                        self.botdecision()
                        self.checkwinner('O','Bot')
        if pos==8:
            if self.box8.text()=='':
                if  (self.box1.text()!='' and self.box2.text()!='' and self.box3.text()!='' and self.box4.text()!='' and self.box5.text()!='' and self.box6.text()!='' and self.box7.text()!='' and self.box8.text()=='' and self.box9.text()!=''):
                        self.box8.setText('X')
                        self.checkwinner('X','You')  
                else:
                        self.box8.setText('X')
                        self.checkwinner('X','You')
                        self.botdecision()
                        self.checkwinner('O','Bot')
        if pos==9:
            if self.box9.text()=='':
                if  (self.box1.text()!='' and self.box2.text()!='' and self.box3.text()!='' and self.box4.text()!='' and self.box5.text()!='' and self.box6.text()!='' and self.box7.text()!='' and self.box8.text()!='' and self.box9.text()==''):
                        self.box9.setText('X')
                        self.checkwinner('X','You')  
                else:
                        
                        self.box9.setText('X')
                        self.checkwinner('X','You')
                        self.botdecision()
                        self.checkwinner('O','Bot')
        

        

    def retranslateUi(self, TicTacToe):
        _translate = QtCore.QCoreApplication.translate
        TicTacToe.setWindowTitle(_translate("TicTacToe", "X/O Game"))
        self.textEdit.setHtml(_translate("TicTacToe", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Rockwell\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Shoutout to ahmad-al-maaz for his hardwork in this masterpiece!!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">For more information contact us at ahmad_maaz@outlook.com</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("TicTacToe", "Welcome to Tic Tac Toe Game !!"))
        self.Reset.setText(_translate("TicTacToe", "Reset"))
        self.Exit.setText(_translate("TicTacToe", "Exit"))
        self.yourscore.setText(_translate("TicTacToe", "Your Score:"))
        self.aiscore.setText(_translate("TicTacToe", "AI Score:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TicTacToe = QtWidgets.QMainWindow()
    ui = Ui_TicTacToe()
    ui.setupUi(TicTacToe)
    TicTacToe.show()
    sys.exit(app.exec_())
