# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Desktop/loginmenu2/loginmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginMenu(object):
    def setupUi(self, LoginMenu):
        LoginMenu.setObjectName("LoginMenu")
        LoginMenu.resize(311, 448)
        LoginMenu.setStyleSheet("background-color: rgb(255, 255, 255);")
        LoginMenu.setDocumentMode(False)
        LoginMenu.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(LoginMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 581, 421))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(-20, 0, 321, 411))
        self.label.setObjectName("label")
        self.submitlogin = QtWidgets.QPushButton(self.page)
        self.submitlogin.setGeometry(QtCore.QRect(160, 215, 51, 20))
        self.submitlogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitlogin.setAutoFillBackground(False)
        self.submitlogin.setStyleSheet("background-color: rgb(244, 65, 65);\n"
"")
        self.submitlogin.setFlat(True)
        self.submitlogin.setObjectName("submitlogin")
        self.emaillogin = QtWidgets.QLineEdit(self.page)
        self.emaillogin.setGeometry(QtCore.QRect(110, 120, 151, 31))
        self.emaillogin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.emaillogin.setInputMethodHints(QtCore.Qt.ImhSensitiveData|QtCore.Qt.ImhTime)
        self.emaillogin.setObjectName("emaillogin")
        self.passworldlogin = QtWidgets.QLineEdit(self.page)
        self.passworldlogin.setGeometry(QtCore.QRect(110, 160, 151, 31))
        self.passworldlogin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.passworldlogin.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferNumbers)
        self.passworldlogin.setObjectName("passworldlogin")
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 370, 281, 31))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("\n"
"background-color: rgb(244, 65, 65);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(156, 50, 61, 20))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(-20, 0, 321, 411))
        self.label_2.setObjectName("label_2")
        self.emailsignup = QtWidgets.QLineEdit(self.page_2)
        self.emailsignup.setGeometry(QtCore.QRect(110, 120, 151, 31))
        self.emailsignup.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.emailsignup.setObjectName("emailsignup")
        self.passworldsignup = QtWidgets.QLineEdit(self.page_2)
        self.passworldsignup.setGeometry(QtCore.QRect(110, 160, 151, 31))
        self.passworldsignup.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.passworldsignup.setObjectName("passworldsignup")
        self.submitsignup = QtWidgets.QPushButton(self.page_2)
        self.submitsignup.setGeometry(QtCore.QRect(150, 210, 71, 31))
        self.submitsignup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitsignup.setAutoFillBackground(False)
        self.submitsignup.setStyleSheet("")
        self.submitsignup.setFlat(True)
        self.submitsignup.setObjectName("submitsignup")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(160, 50, 61, 20))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"text-color:red;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setLineWidth(2)
        self.label_3.setText("")
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(-10, -10, 91, 91))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_2)
        LoginMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 311, 21))
        self.menubar.setObjectName("menubar")
        LoginMenu.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(LoginMenu)
        self.statusBar.setObjectName("statusBar")
        LoginMenu.setStatusBar(self.statusBar)

        self.retranslateUi(LoginMenu)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(LoginMenu)

    def retranslateUi(self, LoginMenu):
        _translate = QtCore.QCoreApplication.translate
        LoginMenu.setWindowTitle(_translate("LoginMenu", "MainWindow"))
        self.label.setText(_translate("LoginMenu", "<html><head/><body><p><img src=\":/newPrefix/11-Actionable-Tips-to-Design-the-Best-Login-Page-thumbnail.png\"/></p></body></html>"))
        self.submitlogin.setText(_translate("LoginMenu", "Sign in"))
        self.pushButton_3.setText(_translate("LoginMenu", "Dont have an account? press here to register"))
        self.label_2.setText(_translate("LoginMenu", "<html><head/><body><p><img src=\":/newPrefix/11-Actionable-Tips-to-Design-the-Best-Login-Page-thumbnail.png\"/></p></body></html>"))
        self.submitsignup.setText(_translate("LoginMenu", "Sign up"))
        self.label_4.setText(_translate("LoginMenu", "<html><head/><body><p><img src=\":/newPrefix/icons8_back_to_100px.png\"/></p></body></html>"))
import logo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginMenu = QtWidgets.QMainWindow()
    ui = Ui_LoginMenu()
    ui.setupUi(LoginMenu)
    LoginMenu.show()
    sys.exit(app.exec_())
