# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\AHMAD\Desktop\hangmandesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import final
from PyQt5 import QtCore, QtGui, QtWidgets
import random
newword=' '
slash=''
finalword=''
lives=6
Yourscore=0
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 600, 500))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setMouseTracking(True)
        self.frame.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 600, 51))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label.setMouseTracking(True)
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 81 26pt \"Rockwell Extra Bold\";\n"
"color:white;\n"
"text-align:center;\n"
"border:2px dashed white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(120, 350, 341, 41))
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.label_2.setMouseTracking(True)
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 81 21pt \"Rockwell Extra Bold\";\n"
"color:white;\n"
"text-align:center;\n"
"border:2px dashed white;\n"
"padding-bottom:8px;\n"
"border-radius:20px;\n"
"")
        self.label_2.setObjectName("label_2")
        self.Abutton = QtWidgets.QPushButton(self.frame)
        self.Abutton.setGeometry(QtCore.QRect(110, 280, 21, 21))
        self.Abutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Abutton.setMouseTracking(True)
        self.Abutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Abutton.setObjectName("Abutton")
        self.Bbutton = QtWidgets.QPushButton(self.frame)
        self.Bbutton.setGeometry(QtCore.QRect(140, 280, 21, 21))
        self.Bbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Bbutton.setMouseTracking(True)
        self.Bbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Bbutton.setObjectName("Bbutton")
        self.Cbutton = QtWidgets.QPushButton(self.frame)
        self.Cbutton.setGeometry(QtCore.QRect(170, 280, 21, 21))
        self.Cbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cbutton.setMouseTracking(True)
        self.Cbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Cbutton.setObjectName("Cbutton")
        self.Dbutton = QtWidgets.QPushButton(self.frame)
        self.Dbutton.setGeometry(QtCore.QRect(200, 280, 21, 21))
        self.Dbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Dbutton.setMouseTracking(True)
        self.Dbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Dbutton.setObjectName("Dbutton")
        self.Ebutton = QtWidgets.QPushButton(self.frame)
        self.Ebutton.setGeometry(QtCore.QRect(230, 280, 21, 21))
        self.Ebutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Ebutton.setMouseTracking(True)
        self.Ebutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Ebutton.setObjectName("Ebutton")
        self.Fbutton = QtWidgets.QPushButton(self.frame)
        self.Fbutton.setGeometry(QtCore.QRect(260, 280, 21, 21))
        self.Fbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Fbutton.setMouseTracking(True)
        self.Fbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Fbutton.setObjectName("Fbutton")
        self.Gbutton = QtWidgets.QPushButton(self.frame)
        self.Gbutton.setGeometry(QtCore.QRect(290, 280, 21, 21))
        self.Gbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Gbutton.setMouseTracking(True)
        self.Gbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Gbutton.setObjectName("Gbutton")
        self.Hbutton = QtWidgets.QPushButton(self.frame)
        self.Hbutton.setGeometry(QtCore.QRect(320, 280, 21, 21))
        self.Hbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Hbutton.setMouseTracking(True)
        self.Hbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Hbutton.setObjectName("Hbutton")
        self.Ibutton = QtWidgets.QPushButton(self.frame)
        self.Ibutton.setGeometry(QtCore.QRect(350, 280, 21, 21))
        self.Ibutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Ibutton.setMouseTracking(True)
        self.Ibutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Ibutton.setObjectName("Ibutton")
        self.Jbutton = QtWidgets.QPushButton(self.frame)
        self.Jbutton.setGeometry(QtCore.QRect(380, 280, 21, 21))
        self.Jbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Jbutton.setMouseTracking(True)
        self.Jbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Jbutton.setObjectName("Jbutton")
        self.Kbutton = QtWidgets.QPushButton(self.frame)
        self.Kbutton.setGeometry(QtCore.QRect(410, 280, 21, 21))
        self.Kbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Kbutton.setMouseTracking(True)
        self.Kbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Kbutton.setObjectName("Kbutton")
        self.Lbutton = QtWidgets.QPushButton(self.frame)
        self.Lbutton.setGeometry(QtCore.QRect(440, 280, 21, 21))
        self.Lbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Lbutton.setMouseTracking(True)
        self.Lbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Lbutton.setObjectName("Lbutton")
        self.Mbutton = QtWidgets.QPushButton(self.frame)
        self.Mbutton.setGeometry(QtCore.QRect(470, 280, 21, 21))
        self.Mbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Mbutton.setMouseTracking(True)
        self.Mbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Mbutton.setObjectName("Mbutton")
        self.Nbutton = QtWidgets.QPushButton(self.frame)
        self.Nbutton.setGeometry(QtCore.QRect(110, 310, 21, 21))
        self.Nbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Nbutton.setMouseTracking(True)
        self.Nbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Nbutton.setObjectName("Nbutton")
        self.Obutton = QtWidgets.QPushButton(self.frame)
        self.Obutton.setGeometry(QtCore.QRect(140, 310, 21, 21))
        self.Obutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Obutton.setMouseTracking(True)
        self.Obutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Obutton.setObjectName("Obutton")
        self.Pbutton = QtWidgets.QPushButton(self.frame)
        self.Pbutton.setGeometry(QtCore.QRect(170, 310, 21, 21))
        self.Pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Pbutton.setMouseTracking(True)
        self.Pbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Pbutton.setObjectName("Pbutton")
        self.Qbutton = QtWidgets.QPushButton(self.frame)
        self.Qbutton.setGeometry(QtCore.QRect(200, 310, 21, 21))
        self.Qbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Qbutton.setMouseTracking(True)
        self.Qbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Qbutton.setObjectName("Qbutton")
        self.Rbutton = QtWidgets.QPushButton(self.frame)
        self.Rbutton.setGeometry(QtCore.QRect(230, 310, 21, 21))
        self.Rbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Rbutton.setMouseTracking(True)
        self.Rbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Rbutton.setObjectName("Rbutton")
        self.Sbutton = QtWidgets.QPushButton(self.frame)
        self.Sbutton.setGeometry(QtCore.QRect(260, 310, 21, 21))
        self.Sbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Sbutton.setMouseTracking(True)
        self.Sbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Sbutton.setObjectName("Sbutton")
        self.Tbutton = QtWidgets.QPushButton(self.frame)
        self.Tbutton.setGeometry(QtCore.QRect(290, 310, 21, 21))
        self.Tbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tbutton.setMouseTracking(True)
        self.Tbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Tbutton.setObjectName("Tbutton")
        self.Nbutton_8 = QtWidgets.QPushButton(self.frame)
        self.Nbutton_8.setGeometry(QtCore.QRect(320, 310, 21, 21))
        self.Nbutton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Nbutton_8.setMouseTracking(True)
        self.Nbutton_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Nbutton_8.setObjectName("Nbutton_8")
        self.Ubutton = QtWidgets.QPushButton(self.frame)
        self.Ubutton.setGeometry(QtCore.QRect(320, 310, 21, 21))
        self.Ubutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Ubutton.setMouseTracking(True)
        self.Ubutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Ubutton.setObjectName("Ubutton")
        self.Nbutton_10 = QtWidgets.QPushButton(self.frame)
        self.Nbutton_10.setGeometry(QtCore.QRect(350, 310, 21, 21))
        self.Nbutton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Nbutton_10.setMouseTracking(True)
        self.Nbutton_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Nbutton_10.setObjectName("Nbutton_10")
        self.Wbutton = QtWidgets.QPushButton(self.frame)
        self.Wbutton.setGeometry(QtCore.QRect(380, 310, 21, 21))
        self.Wbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Wbutton.setMouseTracking(True)
        self.Wbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Wbutton.setObjectName("Wbutton")
        self.Nbutton_12 = QtWidgets.QPushButton(self.frame)
        self.Nbutton_12.setGeometry(QtCore.QRect(350, 310, 21, 21))
        self.Nbutton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Nbutton_12.setMouseTracking(True)
        self.Nbutton_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Nbutton_12.setObjectName("Nbutton_12")
        self.Ubutton_2 = QtWidgets.QPushButton(self.frame)
        self.Ubutton_2.setGeometry(QtCore.QRect(350, 310, 21, 21))
        self.Ubutton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Ubutton_2.setMouseTracking(True)
        self.Ubutton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Ubutton_2.setObjectName("Ubutton_2")
        self.Xbutton = QtWidgets.QPushButton(self.frame)
        self.Xbutton.setGeometry(QtCore.QRect(410, 310, 21, 21))
        self.Xbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Xbutton.setMouseTracking(True)
        self.Xbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Xbutton.setObjectName("Xbutton")
        self.Ybutton = QtWidgets.QPushButton(self.frame)
        self.Ybutton.setGeometry(QtCore.QRect(440, 310, 21, 21))
        self.Ybutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Ybutton.setMouseTracking(True)
        self.Ybutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Ybutton.setObjectName("Ybutton")
        self.Zbutton = QtWidgets.QPushButton(self.frame)
        self.Zbutton.setGeometry(QtCore.QRect(470, 310, 21, 21))
        self.Zbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Zbutton.setMouseTracking(True)
        self.Zbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.Zbutton.setObjectName("Zbutton")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(140, 90, 20, 161))
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.label_3.setMouseTracking(True)
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(160, 90, 100, 20))
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.label_4.setMouseTracking(True)
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(240, 110, 20, 41))
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.label_5.setMouseTracking(True)
        self.label_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.head = QtWidgets.QLabel(self.frame)
        self.head.setGeometry(QtCore.QRect(240, 150, 21, 21))
        self.head.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.head.setMouseTracking(True)
        self.head.setStyleSheet("\n"
"border-radius:10px;")
        self.head.setText("")
        self.head.setObjectName("head")
        self.body = QtWidgets.QLabel(self.frame)
        self.body.setGeometry(QtCore.QRect(246, 170, 8, 41))
        self.body.setStyleSheet("")
        self.body.setText("")
        self.body.setObjectName("body")
        self.rightarm = QtWidgets.QLabel(self.frame)
        self.rightarm.setGeometry(QtCore.QRect(254, 175, 17, 8))
        self.rightarm.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.rightarm.setMouseTracking(True)
        self.rightarm.setStyleSheet("")
        self.rightarm.setText("")
        self.rightarm.setObjectName("rightarm")
        self.leftarm = QtWidgets.QLabel(self.frame)
        self.leftarm.setGeometry(QtCore.QRect(229, 175, 17, 8))
        self.leftarm.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.leftarm.setMouseTracking(True)
        self.leftarm.setStyleSheet("")
        self.leftarm.setText("")
        self.leftarm.setObjectName("leftarm")
        self.rightleg = QtWidgets.QLabel(self.frame)
        self.rightleg.setGeometry(QtCore.QRect(254, 203, 18, 8))
        self.rightleg.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.rightleg.setMouseTracking(True)
        self.rightleg.setStyleSheet("")
        self.rightleg.setText("")
        self.rightleg.setObjectName("rightleg")
        self.leftleg = QtWidgets.QLabel(self.frame)
        self.leftleg.setGeometry(QtCore.QRect(229, 203, 18, 8))
        self.leftleg.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.leftleg.setMouseTracking(True)
        self.leftleg.setStyleSheet("")
        self.leftleg.setText("")
        self.leftleg.setObjectName("leftleg")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(210, 430, 180, 60))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 36pt \"Viner Hand ITC\";\n"
"border:2px solid black;\n"
"border-radius:15px;")
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(460, 90, 121, 151))
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.textEdit.setStyleSheet("font: 14pt \"Rockwell\";\n"
"border-color: rgb(0, 0, 0);\n"
"border: 3px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.yourscore = QtWidgets.QLabel(self.frame)
        self.yourscore.setGeometry(QtCore.QRect(10, 435, 161, 41))
        self.yourscore.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.yourscore.setMouseTracking(True)
        self.yourscore.setStyleSheet("font: 18pt \"Segoe Print\";\n"
"text-decoration: line-through;")
        self.yourscore.setObjectName("yourscore")
        self.Timespent = QtWidgets.QLabel(self.frame)
        self.Timespent.setGeometry(QtCore.QRect(410, 435, 161, 41))
        self.Timespent.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.Timespent.setMouseTracking(True)
        self.Timespent.setStyleSheet("font: 18pt \"Segoe Print\";\n"
"text-decoration: line-through;")
        self.Timespent.setObjectName("Timespent")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #my code
        Words=['jelly','luxury','lucky','yummy','zombie','football','basketball','pronunciation','digital','jelly','google','laptop','apple','orange','wave','juice','bitcoin','ahmad','development','camping','coding','sheesh','fortnite','microwave','kitchen','school','college','maaz','hangman','videogame','python','create','bitcoin','lebanon','syndrome','border','discussion','garage','grandmother','independent','brick','memory','mathematics','require','tobacco','sylvester','kuku','quicksand','frame','space','control','elonmusk','army','germany','daughter','lunchroom','heart','arrdee','ring','johncena','machine','website','brick','pocket','design','hammer','sea','river','notebook','digestion','skirt','lettuce','society','attraction','vegetable','passenger','friction','history','birthday','text','party','stranger','connection','minute','rabbit','aya','mailbox','bedroom','building','chicken','language','system','copper','country','pancake','airport','dogshit','invention','umbrella','cow','tank','channel','treatment','pollution']
        self.Abutton.clicked.connect(lambda: checkletter('a'))
        self.Bbutton.clicked.connect(lambda: checkletter('b'))
        self.Cbutton.clicked.connect(lambda: checkletter('c'))
        self.Dbutton.clicked.connect(lambda: checkletter('d'))
        self.Ebutton.clicked.connect(lambda: checkletter('e'))
        self.Fbutton.clicked.connect(lambda: checkletter('f'))
        self.Gbutton.clicked.connect(lambda: checkletter('g'))
        self.Hbutton.clicked.connect(lambda: checkletter('h'))
        self.Ibutton.clicked.connect(lambda: checkletter('i'))
        self.Jbutton.clicked.connect(lambda: checkletter('j'))
        self.Kbutton.clicked.connect(lambda: checkletter('k'))
        self.Lbutton.clicked.connect(lambda: checkletter('l'))
        self.Mbutton.clicked.connect(lambda: checkletter('m'))
        self.Nbutton.clicked.connect(lambda: checkletter('n'))
        self.Obutton.clicked.connect(lambda: checkletter('o'))
        self.Pbutton.clicked.connect(lambda: checkletter('p'))
        self.Qbutton.clicked.connect(lambda: checkletter('q'))
        self.Rbutton.clicked.connect(lambda: checkletter('r'))
        self.Sbutton.clicked.connect(lambda: checkletter('s'))
        self.Tbutton.clicked.connect(lambda: checkletter('t'))
        self.Ubutton.clicked.connect(lambda: checkletter('u'))
        self.Ubutton_2.clicked.connect(lambda: checkletter('v'))
        self.Wbutton.clicked.connect(lambda: checkletter('w'))
        self.Xbutton.clicked.connect(lambda: checkletter('x'))
        self.Ybutton.clicked.connect(lambda: checkletter('y'))
        self.Zbutton.clicked.connect(lambda: checkletter('z'))
        self.pushButton.clicked.connect(lambda: rset())

        
        #to color button green or red
        def greenorred(letter,color):
          if letter=='a': self.Abutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='b': self.Bbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='c': self.Cbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='d': self.Dbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='e': self.Ebutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='f': self.Fbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='g': self.Gbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='h': self.Hbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='i': self.Ibutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='j': self.Jbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='l': self.Lbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='m': self.Mbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='n': self.Nbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='o': self.Obutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='p': self.Pbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='k': self.Kbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='q': self.Qbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='r': self.Rbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='s': self.Sbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='t': self.Tbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='u': self.Ubutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='v': self.Ubutton_2.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='w': self.Wbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='x': self.Xbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='y': self.Ybutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))
          elif letter=='z': self.Zbutton.setStyleSheet("background-color:{0};border:1px solid black;".format(color))

        #to disable or enable buttons
        def enableordisable(condition):
                self.Abutton.setEnabled(condition)
                self.Bbutton.setEnabled(condition)        
                self.Cbutton.setEnabled(condition)        
                self.Dbutton.setEnabled(condition)                
                self.Ebutton.setEnabled(condition)        
                self.Fbutton.setEnabled(condition)        
                self.Gbutton.setEnabled(condition)        
                self.Hbutton.setEnabled(condition)        
                self.Ibutton.setEnabled(condition)        
                self.Jbutton.setEnabled(condition)        
                self.Kbutton.setEnabled(condition)        
                self.Lbutton.setEnabled(condition)
                self.Rbutton.setEnabled(condition)          
                self.Mbutton.setEnabled(condition)        
                self.Nbutton.setEnabled(condition)        
                self.Obutton.setEnabled(condition)        
                self.Pbutton.setEnabled(condition)        
                self.Qbutton.setEnabled(condition)        
                self.Sbutton.setEnabled(condition)        
                self.Tbutton.setEnabled(condition)        
                self.Ubutton.setEnabled(condition)        
                self.Ubutton_2.setEnabled(condition)        
                self.Wbutton.setEnabled(condition)        
                self.Xbutton.setEnabled(condition)        
                self.Ybutton.setEnabled(condition)        
                self.Zbutton.setEnabled(condition)
        # to set newword
        def setnewword():
          number= random.randint(0,len(Words)-1)
          if len(Words[number])<14:
                global newword,finalword
                newword=Words[number]
                finalword=newword
                Words.remove(Words[number])
          for number in range(0,len(newword)):
            global slash
            slash+='_'
            #slash+=' '
            self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);font: 81 16pt Rockwell Extra Bold;color:white;text-align:center;border:2px dashed white;padding-bottom:8px;border-radius:20px;")
            self.label_2.setText('       {0}       //length:{1}' .format(slash,len(newword)))
        # function for reset button 
        def rset():
                global newword,slash,lives,finalword
                newword=' '
                slash=''
                finalword=''
                lives=6
                setnewword()
                enableordisable(True)
                self.head.setStyleSheet('background-color:rgb(255, 170, 255);border-radius:10px;')
                self.rightarm.setStyleSheet('background-color:rgb(255, 170, 255);')
                self.leftarm.setStyleSheet('background-color:rgb(255, 170, 255);')
                self.rightleg.setStyleSheet('background-color:rgb(255, 170, 255);')
                self.leftleg.setStyleSheet('background-color:rgb(255, 170, 255);')
                self.body.setStyleSheet('background-color:rgb(255, 170, 255);')
                self.label.setStyleSheet('background-color: rgb(0, 0, 0);font: 81 26pt "Rockwell Extra Bold";color:white;text-align:center;border:2px dashed white;')
                self.label.setText('               Hangman Game')
                self.label_2.setText('       {0}     //length:{1}' .format(slash,len(newword)))
                Letters=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
                for letter in Letters:
                        greenorred(letter,'white')

        def checkletter(letter):
          global newword,slash,lives,Yourscore
          if letter in newword:
                index1=newword.index(letter)
                string2=list(newword)
                string2[index1]='&'
                newword=''.join(string2)
                if letter in newword:
                        index2=newword.index(letter)
                        slashlist=list(slash)
                        slashlist[index1]=letter
                        slashlist[index2]=letter
                        slash=''.join(slashlist)
                        greenorred(letter,'green')
                        self.label_2.setText('       {0}     //length:{1}' .format(slash,len(newword)))
                        
                else:
                        
                        slashlist=list(slash)
                        slashlist[index1]=letter
                        slash=''.join(slashlist)
                        greenorred(letter,'green')
                        self.label_2.setText('       {0}     //length:{1}' .format(slash,len(newword)))
          # this else  statement 
          else:
                greenorred(letter,'red')
                if lives==6:
                        self.head.setStyleSheet('background-color:white;border-radius:10px;')
                        lives-=1
                elif lives==5:
                        self.body.setStyleSheet('background-color:white')
                        lives-=1
                elif lives==4:
                        self.rightarm.setStyleSheet('background-color:white')
                        lives-=1
                elif lives==3:
                        self.leftarm.setStyleSheet('background-color:white')
                        lives-=1
                elif lives==2:
                        self.rightleg.setStyleSheet('background-color:white')
                        lives-=1
                elif lives==1:
                        self.label_2.setStyleSheet("background-color: red;font: 81 16pt Rockwell Extra Bold;color:white;text-align:center;border:2px dashed white;padding-bottom:8px;border-radius:20px;color:black")
                        self.leftleg.setStyleSheet('background-color:white')
                        self.label_2.setText('       {0}     //length:{1}' .format(finalword,len(newword)))
                        self.label.setText('                      YOU LOST!')
                        self.label.setStyleSheet('background-color: red;font: 81 26pt "Rockwell Extra Bold";color:black;text-align:center;border:2px dashed white;')
                        Yourscore-=1
                        self.yourscore.setText('Your score:{0}'.format(Yourscore))
                        enableordisable(False)
          #to check if u won or smthg 
          if slash==finalword:
                Yourscore+=1
                self.yourscore.setText('Your score:{0}'.format(Yourscore))
                self.label.setText('                      YOU WON!')
                self.label.setStyleSheet('background-color: green;font: 81 26pt "Rockwell Extra Bold";color:black;text-align:center;border:2px dashed white;')
                enableordisable(False)
          
          # to disable every button when it is pressed
          if letter=='a': self.Abutton.setEnabled(False)
          elif letter=='b': self.Bbutton.setEnabled(False)
          elif letter=='c': self.Cbutton.setEnabled(False)
          elif letter=='d': self.Dbutton.setEnabled(False)
          elif letter=='e': self.Ebutton.setEnabled(False)
          elif letter=='f': self.Fbutton.setEnabled(False)
          elif letter=='g': self.Gbutton.setEnabled(False)
          elif letter=='h': self.Hbutton.setEnabled(False)
          elif letter=='i': self.Ibutton.setEnabled(False)
          elif letter=='j': self.Jbutton.setEnabled(False)
          elif letter=='l': self.Lbutton.setEnabled(False)
          elif letter=='m': self.Mbutton.setEnabled(False)
          elif letter=='n': self.Nbutton.setEnabled(False)
          elif letter=='o': self.Obutton.setEnabled(False)
          elif letter=='p': self.Pbutton.setEnabled(False)
          elif letter=='k': self.Kbutton.setEnabled(False)
          elif letter=='q': self.Qbutton.setEnabled(False)
          elif letter=='r': self.Rbutton.setEnabled(False)
          elif letter=='s': self.Sbutton.setEnabled(False)
          elif letter=='t': self.Tbutton.setEnabled(False)
          elif letter=='u': self.Ubutton.setEnabled(False)
          elif letter=='v': self.Ubutton_2.setEnabled(False)
          elif letter=='w': self.Wbutton.setEnabled(False)
          elif letter=='x': self.Xbutton.setEnabled(False)
          elif letter=='y': self.Ybutton.setEnabled(False)
          elif letter=='z': self.Zbutton.setEnabled(False)

                        

        setnewword()
        
        self.Timespent.setText('')
#till here
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ahmad-Al-Maaz"))
        self.label.setText(_translate("MainWindow", "               Hangman Game"))
        self.label_2.setText(_translate("MainWindow", " _ _ _ _ _ _ _ _ _ _ _ _ _ _ "))
        self.Abutton.setText(_translate("MainWindow", "A"))
        self.Bbutton.setText(_translate("MainWindow", "B"))
        self.Cbutton.setText(_translate("MainWindow", "C"))
        self.Dbutton.setText(_translate("MainWindow", "D"))
        self.Ebutton.setText(_translate("MainWindow", "E"))
        self.Fbutton.setText(_translate("MainWindow", "F"))
        self.Gbutton.setText(_translate("MainWindow", "G"))
        self.Hbutton.setText(_translate("MainWindow", "H"))
        self.Ibutton.setText(_translate("MainWindow", "I"))
        self.Jbutton.setText(_translate("MainWindow", "J"))
        self.Kbutton.setText(_translate("MainWindow", "K"))
        self.Lbutton.setText(_translate("MainWindow", "L"))
        self.Mbutton.setText(_translate("MainWindow", "M"))
        self.Nbutton.setText(_translate("MainWindow", "N"))
        self.Obutton.setText(_translate("MainWindow", "O"))
        self.Pbutton.setText(_translate("MainWindow", "P"))
        self.Qbutton.setText(_translate("MainWindow", "Q"))
        self.Rbutton.setText(_translate("MainWindow", "R"))
        self.Sbutton.setText(_translate("MainWindow", "S"))
        self.Tbutton.setText(_translate("MainWindow", "T"))
        self.Nbutton_8.setText(_translate("MainWindow", "N"))
        self.Ubutton.setText(_translate("MainWindow", "U"))
        self.Nbutton_10.setText(_translate("MainWindow", "N"))
        self.Wbutton.setText(_translate("MainWindow", "W"))
        self.Nbutton_12.setText(_translate("MainWindow", "N"))
        self.Ubutton_2.setText(_translate("MainWindow", "V"))
        self.Xbutton.setText(_translate("MainWindow", "X"))
        self.Ybutton.setText(_translate("MainWindow", "Y"))
        self.Zbutton.setText(_translate("MainWindow", "Z"))
        self.pushButton.setText(_translate("MainWindow", "Reset"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Rockwell\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Shoutout to ahmad-al-maaz for his hardwork in this masterpiece!!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.yourscore.setText(_translate("MainWindow", "You Score:"))
        self.Timespent.setText(_translate("MainWindow", "Time:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

